### ISSUE TITLE
任务一

### ISSUE THREAD

**Issue by muxiaobai** [muxiaobai/SSH#1]
[http://pan.baidu.com/s/1pLIOmO7](http://pan.baidu.com/s/1pLIOmO7)
github离线安装包，
# 今天的任务：

先下载/otherData/old.epf,基本eclipse配置，编码等。
然后把github上的SSH框架在本机装好。
基本的jar下载完成，运行server  控制台可以出现相关信息。

**Comment by muxiaobai** [comment]
补充说明：导入epf的时候，参考[http://blog.sina.com.cn/s/blog_7dfb07ac01018n04.html](http://blog.sina.com.cn/s/blog_7dfb07ac01018n04.html)
导入SSH的时候，选择Gradle项目，然后Gradle build会下载对应的jar包。

**Comment by zhongzhongBaby** [comment]
好的

**Comment by muxiaobai** [comment]
you are latter boy; @GitHubGYZ

**Comment by zhongzhongBaby** [comment]
I'm  so sorry
